name: Check if tfm updated

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  check-update:
    name: Download SWF and check if the version changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install build-essential
        run: |
          sudo apt-get install -y build-essential

      - name: Set env
        run: |
          echo workspace=$GITHUB_WORKSPACE >> $GITHUB_ENV

      - name: Clone swflib's headers
        run: |
          git clone https://github.com/Athesdrake/swflib

      - name: Compile program
        run: |
          gcc -Wall --std=c++17 ./check-version.cpp -o ./check-version.o -I${{ env.workspace }}/swflib/include -L${{ env.workspace }} -lswflib -lstdc++
          chmod +x ./check-version.o

      - name: Download SWF
        run: |
          curl -L http://transformice.com/Transformice.swf > Transformice.swf

      - name: Check if the game has been updated
        run: |
          ./check-version.o
